stages:
  - lint
  - test
  - build
  - docker

variables:
  PYTHON_VERSION: "3.10"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

  PREFIX: "functions"
  NAME: "litellm"
  NAMESPACE: "console"


# test:
#   stage: test
#   image: python:$PYTHON_VERSION
#   script:
#     - pip install pytest
#     - pytest tests/litellm

#build:
#  stage: build
#  image: python:$PYTHON_VERSION
#  script:
#    - pip install build
#    - python -m build
#  artifacts:
#    paths:
#      - dist/

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - echo "$HARBOR_PASSWORD" | docker login --username "$HARBOR_USERNAME" "$HARBOR_HOST" --password-stdin
  after_script:
    - docker logout
  script:
    - DATE=$(date +'%y%m%d') # Generates '250516' for May 16, 2025
    - VERSION_TAG="${DATE}"
    - "TAG=${HARBOR_HOST}/${HARBOR_PROJECT}/${NAMESPACE}/${PREFIX}/${NAME}:${VERSION}"
    - docker build -t $TAG .
    - docker push $TAG
  only:
    - main
